# Change these first
owner: LyridInc # Your GitHub username
repo: statuspage # Your GitHub repository name

# Add your sites here
sites:
  - name: Home - Landing Page
    url: https://lyrid.io/assets/images/resources/logo_transparent.png
  - name: Documentation Page
    url: https://docs.lyrid.io/img/lyridsvg.svg
  - name: API Server
    url: https://api.lyrid.io/version
  - name: Authentication Server
    url: https://id.lyrid.io/version

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.lyrid.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /statuspage
  logoUrl: https://lyrid.io/assets/images/resources/logo_transparent.png
  favicon: https://lyrid.io/assets/images/favicons/apple-touch-icon.png
  name: "Lyrid's Status Page"
  themeUrl: https://appify.org/lyrid.css
  introTitle: "Lyrid's Status Page"
  navbar:
    - title: Status Page
      href: /
    - title: Lyrid
      href: https://www.lyrid.io
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

